In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('movie_trailer_temp.csv')

In [37]:
print(f'Phim không có trailer: {df["trailer_url"].isnull().sum()}')

Phim có trailer: 1052

In [4]:
movie=pd.read_csv('movies-new.csv')

In [5]:
movie.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [6]:
#lấy danh sách các thể loại trong bảng movie không trùng lặp
genre=set()
for i in movie['genres']:
    for j in i.split('|'):
        genre.add(j)

In [7]:
print(genre)

{'Romance', 'Crime', 'Children', 'Animation', 'Drama', 'Comedy', '(no genres listed)', 'Action', 'Musical', 'IMAX', 'War', 'Adventure', 'Fantasy', 'Mystery', 'Documentary', 'Horror', 'Film-Noir', 'Thriller', 'Sci-Fi', 'Western'}

In [16]:
no_genre=movie[movie['genres']=='(no genres listed)']
imax=movie[movie['genres'].str.contains('IMAX')]

In [17]:
no_genre.shape

(34, 3)

In [24]:
#xóa các phim không có thể loại và imax
movie = movie[movie['genres'] != '(no genres listed)']
def remove_imax(genres):
    genre_list = [i for i in genres.split('|') if i != 'IMAX']
    return '|'.join(genre_list)
movie['genres'] = movie['genres'].apply(remove_imax)

In [26]:
# lấy lại danh sách phim sau khi cập nhật
genre=set()
for i in movie['genres']:
    for j in i.split('|'):
        genre.add(j)

In [32]:
genre_list=sorted(genre)
print(genre_list)

['Action', 'Adventure', 'Animation', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']

In [28]:
movie.shape

(9708, 3)

In [33]:
def vector(genre, genre_list):
    return [1 if i in genre.split('|') else 0 for i in genre_list]
movie['genre_vector']=movie['genres'].apply(lambda x: vector(x,genre_list))
movie.head()

,movieId,title,genres,genre_vector
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"[0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..."
1,2,Jumanji (1995),Adventure|Children|Fantasy,"[0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..."
2,3,Grumpier Old Men (1995),Comedy|Romance,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ..."
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,"[0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, ..."
4,5,Father of the Bride Part II (1995),Comedy,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [35]:
movie['genre_vector'].iloc[1]

[0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]