In [72]:
import pandas as pd
import numpy as np

In [73]:
movies1=pd.read_csv('movies1.csv')
ratings1=pd.read_csv('ratings1.csv')

In [74]:
movies1.shape

(9742, 3)

In [75]:
ratings1.shape

(100836, 4)

In [71]:
print(ratings1['movieId'].nunique())

9724

In [77]:
ratings2=pd.read_csv('ratings2.csv')

In [88]:
ratings2.rename(columns={'movieId':'movie_id'},inplace=True)

In [89]:
filterss=movie.merge(ratings2,on='movie_id')

In [90]:
print(filterss['movie_id'].nunique())

1375

In [91]:
print(filterss['userId'].nunique())

160550

In [93]:
ratings0=pd.read_csv('ratings0.csv')
ratings_small=pd.read_csv('ratings_small.csv')

In [94]:
ratings0.rename(columns={'movieId':'movie_id'},inplace=True)
ratings_small.rename(columns={'movieId':'movie_id'},inplace=True)

In [95]:
filterss0=movie.merge(ratings0,on='movie_id')
filterss1=movie.merge(ratings_small,on='movie_id')

In [96]:
print(filterss0['movie_id'].nunique())
print(filterss1['movie_id'].nunique())

1355
857

In [97]:
print(filterss0['userId'].nunique())

247466

In [84]:
movie=pd.read_csv('movie.csv')
credit=pd.read_csv('credit.csv')

In [6]:
credit.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [85]:
movie.rename(columns={'id':'movie_id'}, inplace=True)

In [8]:
credit.drop(columns=['title'],inplace=True)

In [9]:
movie=movie.merge(credit,on='movie_id')

In [10]:
movie.head(1)

,budget,genres,homepage,movie_id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [11]:
movie.shape

(4803, 22)

In [12]:
movie=movie[['movie_id','title','overview','genres','keywords','cast','crew']]

In [13]:
movie.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [14]:
movie.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [15]:
movie.dropna(inplace=True)

In [16]:
movie.duplicated().sum()

0

In [17]:
ratings=pd.read_csv('ratings.csv')

In [18]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [19]:
ratings.rename(columns={'movieId':'movie_id'},inplace=True)

In [20]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [21]:
movie['genres']=movie['genres'].apply(convert)

In [22]:
movie.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
movie['keywords']=movie['keywords'].apply(convert)

In [24]:
movie.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
def convert3(obj):
    L=[]
    count=0
    for i in ast.literal_eval(obj):
        count+=1
        if(count<=3):
            L.append(i['name'])
        else:
            break
    return L

In [26]:
movie['cast']=movie['cast'].apply(convert3)

In [27]:
def convert2(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if(i['job']=='Director'):
            L.append(i['name'])
        else:
            continue
    return L

In [28]:
movie['crew']=movie['crew'].apply(convert2)

In [29]:
movie['overview']=movie['overview'].apply(lambda x:x.split())

In [30]:
movie['genres']=movie['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [31]:
movie['cast']=movie['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movie['crew']=movie['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movie['keywords']=movie['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

In [32]:
movie['tag']=movie['overview']+movie['genres']+movie['keywords']+movie['cast']+movie['crew']

In [33]:
movie['tag'].head().iloc[0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [34]:
movie.drop(['genres','keywords','overview','cast','crew'],axis=1,inplace=True)

In [35]:
movie.head()

,movie_id,title,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [36]:
movie['tag']=movie['tag'].apply(lambda x:" ".join(x))

In [37]:
movie.head()

,movie_id,title,tag
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [38]:
movie['tag']=movie['tag'].apply(lambda x: x.lower())

In [39]:
import nltk

In [40]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [41]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [42]:
movie['tag']=movie['tag'].apply(stem)

In [43]:
movie['tag'].iloc[0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [44]:
from sklearn.feature_extraction.text import CountVectorizer

In [45]:
#def remove_numbers(text):
    # Loại bỏ tất cả số
   # text = re.sub(r'\d+', '', text)
   # return text
#movie['tag'] = movie['tag'].apply(remove_numbers)

In [46]:
cv = CountVectorizer(max_features=5000, stop_words='english')

In [47]:
vector=cv.fit_transform(movie['tag']).toarray()

In [48]:
vector.shape

(4800, 5000)

In [49]:
features=cv.get_feature_names_out()

In [50]:
vector[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [51]:
for word in features:
    print(word)

000
007
10
100
11
12
13
14
15
16
17
17th
18
18th
18thcenturi
19
1910
1920
1930
1940
1944
1950
1950s
1960
1960s
1970
1970s
1971
1974
1976
1980
1985
1990
1999
19th
19thcenturi
20
200
2003
2009
20th
21st
23
24
25
30
300
3d
40
50
500
60
70
80
aaron
aaroneckhart
abandon
abduct
abigailbreslin
abil
abl
aboard
abov
abus
academ
academi
accept
access
accid
accident
acclaim
accompani
accomplish
account
accus
ace
achiev
acquaint
act
action
actionhero
activ
activist
activities
actor
actress
actual
ad
adam
adamsandl
adamshankman
adapt
add
addict
adjust
admir
admit
adolesc
adopt
ador
adrienbrodi
adult
adultanim
adulteri
adulthood
advanc
adventur
adventure
adventures
advertis
advic
advis
affair
affect
afghanistan
africa
african
africanamerican
aftercreditssting
afterlif
aftermath
ag
age
agediffer
agenc
agency
agenda
agent
agents
aggress
ago
agre
ahead
aid
aidanquinn
ail
aim
air
airplan
airplanecrash
airport
aka
al
alabama
alan
alaska
albert
alcatraz
alcohol
alecbaldwin
alex
alexkendrick
alfredhitchcock
alfredmolina
ali
alic
alice
alien
alieninvas
alienlife
alienplanet
aliens
alik
aliv
alive
allen
alli
allianc
allow
alon
alongsid
alpacino
alpha
alreadi
alter
altern
alway
alyssa
alzheimer
amanda
amandapeet
amandaseyfri
amateur
amaz
amazon
ambassador
ambit
ambiti
ambul
ambush
america
american
americanabroad
americancivilwar
americanfootbal
americanfootballplay
amid
amidst
amnesia
amp
amsterdam
amus
amusementpark
amy
amyadam
amysmart
ana
anakin
analyst
anarchiccomedi
ancient
ancientrom
ancientworld
anderson
andi
andiemacdowel
andrew
android
andy
andygarcía
angel
angelabassett
angeles
angelinajoli
anger
angle
angri
ani
anim
animalattack
animalhorror
animals
anjelicahuston
ann
anna
annafari
annakendrick
anne
annehathaway
annemoss
annetteben
anni
annie
anniversari
announc
annual
anonym
anoth
answer
ant
antholog
anthoni
anthonyanderson
anthonyhopkin
anthropomorph
anti
antic
antihero
antiqu
antoinefuqua
antoniobandera
antonyelchin
anyon
anyth
apart
apartheid
apartment
ape
apocalyps
apocalypse
apocalypt
appar
appear
appl
apple
appoint
appreci
apprentic
approach
april
aquarium
arab
arch
archaeologist
archeolog
architect
arctic
area
aren
arena
argument
aris
aristocrat
arm
armi
armor
armsdeal
army
arnold
arnoldschwarzenegg
arrang
arrangedmarriag
arrest
arriv
arrog
art
arthur
artifact
artifici
artificialintellig
artist
ash
ashley
ashleyjudd
ashtonkutch
asia
asian
asid
ask
aspect
aspir
assassin
assault
assembl
assign
assist
assistant
associ
assum
asteroid
astronaut
asylum
atheist
athlet
atom
atomicbomb
attack
attacks
attempt
attempttoescap
attend
attent
attic
attitud
attorney
attract
auction
audienc
audit
august
aunt
austin
australia
australian
author
autism
auto
automobilerac
aveng
averag
avoid
await
awak
awaken
awar
award
away
awkward
awri
awry
ax
babe
babi
baby
bachelor
backdrop
background
backpack
bad
bag
bahama
bail
balanc
ball
ballet
balloon
baltimor
ban
band
bandit
bangkok
banish
bank
banker
bankrobb
bankrobberi
bar
barbrastreisand
bare
bargain
barn
barney
baron
barri
barrylevinson
barrysonnenfeld
bas
base
basebal
basedoncomicbook
basedongraphicnovel
basedonnovel
basedonplay
basedonstagemus
basedontrueev
basedontruestori
basedontvseri
basedonvideogam
basedonyoungadultnovel
basement
basketbal
basketball
bat
batman
battl
battle
battlefield
bay
beach
beam
bear
beard
beast
beat
beauti
beautiful
beautifulwoman
beauty
becam
becaus
becki
becom
becominganadult
bed
bedroom
bee
beer
befor
befriend
began
begin
begins
behavior
belief
believ
bell
bella
belong
belov
ben
benaffleck
bend
beneath
benefit
benfost
beniciodeltoro
benjamin
benjaminbratt
benkingsley
bennett
benstil
bent
berlin
best
bestfriend
bestfriendsinlov
bet
beth
betray
bettemidl
better
betti
beverli
bibl
bid
big
bigger
biggest
bike
biker
bikini
billhad
billi
billionair
billmurray
billnighi
billpaxton
billpullman
billybobthornton
billycrudup
billycryst
biographi
biolog
bird
birth
birthday
bisexu
bishop
bit
bite
bitter
bizarr
black
blackmag
blackmail
blackpeopl
blacksmith
blade
blame
blend
blind
bliss
blizzard
block
blond
blood
bloodi
bloodsplatt
bloodthirsti
blow
blue
board
boardingschool
boat
bob
bobbi
bobbyfarrelli
bobhoskin
bodi
body
bodyguard
bold
bollywood
bomb
bond
bone
book
border
bore
boredom
born
boss
boston
botch
bound
boundari
bounti
bountyhunt
bout
box
boxer
boy
boyfriend
boys
bradleycoop
bradpitt
brain
brainwash
brand
brandon
brave
braveri
brazil
brazilian
break
breakdown
breakup
breast
breath
breed
brendanfras
brendangleeson
brent
brettratn
brian
briandepalma
bride
bridesmaid
bridg
brief
brielarson
brien
bright
brilliant
bring
brink
britain
british
britishsecretservic
brittanymurphi
broadcast
broadway
broke
broken
broker
bronx
brook
brooklyn
broom
brothel
brother
brotherbrotherrelationship
brothers
brothersisterrelationship
brought
brown
bruce
brucegreenwood
brucewilli
brutal
bryansing
bu
buck
bud
buddi
buddy
buddycomedi
buddycop
budget
build
building
built
bullet
bulli
bumbl
bunch
bunker
bunni
burglar
buri
burn
bush
busi
business
businessman
bust
butcher
butler
butt
button
buy
buzz
cabin
caesar
cage
cairo
cal
california
calvin
camcord
came
camera
cameraman
camerondiaz
camp
campaign
campbell
campu
canada
canadian
cancer
candi
candid
canin
cannib
canuxploit
capabl
caper
capit
capt
captain
captiv
captur
capture
car
caraccid
carchas
carcrash
card
care
career
carefre
caretak
careymulligan
caribbean
carjourney
carl
carlagugino
carmen
carol
carolina
carrac
carri
carrie
cartel
carter
cartoon
caryelw
case
caseyaffleck
cash
casino
cast
castl
cat
cataclysm
catastroph
catch
cateblanchett
catherinedeneuv
catherinekeen
catherinezeta
cathol
catholic
cattl
caught
caus
cavalri
cave
cavemen
celebr
celebration
cell
cellphon
cemeteri
center
centr
central
centuri
centuries
century
ceo
certain
chad
chain
chainsaw
challeng
chamber
champion
championship
chanc
chance
chang
change
changed
changes
channingtatum
chao
chaos
chaotic
chapter
charact
character
characters
charg
charismat
charl
charli
charlie
charliesheen
charlizetheron
charm
chart
chase
chauffeur
chazzpalminteri
cheat
check
cheerlead
chef
chemic
cher
chevychas
chicago
chicken
chief
child
childabus
childhero
childhood
childprodigi
children
chill
chimp
china
chines
chip
chipmunk
chiwetelejiofor
chloe
chloëgracemoretz
chloësevigni
chocol
choic
choice
choos
chosen
chowyun
chri
chriscolumbu
chriscoop
chrisevan
chrishemsworth
chrisklein
chrispin
chrisrock
christ
christian
christianbal
christianslat
christin
christinaappleg
christinaricci
christma
christmas
christmasparti
christmastre
christoph
christopherlambert
christopherlloyd
christophernolan
christopherplumm
christopherwalken
christophwaltz
chrisweitz
chronicl
chuck
church
cia
ciaránhind
cigarettesmok
cillianmurphi
cinema
circl
circu
circuit
circumst
citi
citizen
city
civil
civilian
civilwar
claim
clair
clairedan
claireforlani
clan
clark
clash
class
classdiffer
classic
classmat
classroom
claudevandamm
clay
clean
clear
clerk
clever
client
clients
cliff
climat
climb
clinteastwood
cliveowen
clock
clone
close
closer
cloud
clown
club
clue
clueless
clutch
coach
coast
cocain
code
coffin
cohen
col
cold
coldwar
cole
colin
colinfarrel
colinfirth
collaps
colleagu
collect
collector
colleg
college
collid
collis
colombia
colonel
coloni
color
colorado
coma
combat
combin
come
comeback
comed
comedi
comedian
comedy
comet
comfort
comic
coming
comingofag
comingout
command
commando
commerci
commiss
commit
common
commun
communist
community
compani
companion
company
compet
competit
competition
complet
complex
complic
compos
compuls
comput
computerviru
conan
concern
concert
concoct
condit
condition
conduct
confeder
confess
confid
confin
conflict
confront
confus
congress
conman
connect
connecticut
connel
connor
conquer
consequ
consequences
conserv
consid
conspir
conspiraci
conspiracy
constant
constantli
construct
consum
contact
contain
contemporari
contend
content
contest
continu
contract
contractor
control
controversi
convent
converg
convers
convict
convinc
cook
cool
cooper
cop
cope
cops
core
corner
corp
corpor
corporation
corps
corrupt
cost
costum
couldn
counselor
count
countess
countless
countri
country
countryhous
countrymus
countrysid
coup
coupl
couple
courag
cours
court
courtcas
courteneycox
courtroom
cousin
cover
covert
covet
cow
cowardli
cowboy
crab
crack
craft
craig
crane
crash
crave
crazi
creat
creation
creativ
creator
creatur
creature
creatures
credit
creepi
crew
cri
crime
crimefight
crimes
crimin
criminal
criminals
crisi
crisis
critic
crocodil
crook
cross
crossdress
crowd
crown
crucifixion
cruel
cruelti
cruis
crusad
crush
crystal
cuba
cubagoodingjr
culmin
cult
cultfilm
cultur
culture
cultureclash
cun
cup
cure
current
curs
curse
curtishanson
custodi
custom
cut
cuttingthecord
cyberpunk
cyborg
cynic
dad
daili
dakotafan
dale
damag
damon
dan
danaykroyd
danc
dancer
danger
daniel
danielcraig
danielday
danielradcliff
danni
danny
dannyboyl
dannydevito
dannyglov
dare
dark
darkcomedi
darkest
darkness
darylhannah
dash
date
daughter
daughters
dave
davi
david
davidarquett
davidcronenberg
davidduchovni
davidfinch
davidgordongreen
davidmors
davido
davidschwimm
davidspad
davidthewli
dawn
daxshepard
day
daydream
days
dc
dccomic
dea
dead
deadli
deadliest
deaf
deal
dealer
dean
death
deathofafriend
deathoffath
deathpenalti
debt
debut
decad
decapit
deceas
deceit
decept
decid
decis
declar
dedic
deed
deep
deeper
deepli
defeat
defend
defens
defi
defin
delight
deliv
deliveri
delus
demand
demimoor
demon
demonicpossess
demons
deni
deniserichard
denmark
denni
dennisdugan
dennishopp
dennisquaid
dentist
denzelwashington
depart
depend
depict
depress
depth
deputi
derang
derek
derekluk
descend
describ
desert
design
desir
desk
desol
despair
desper
despit
destin
destini
destiny
destroy
destroyed
destruct
destruction
detect
detective
determin
detroit
devast
develop
devic
devil
deviou
devis
devot
diabol
diagnos
dialogu
diamond
dian
dianekeaton
dianekrug
dianelan
diari
dick
dictat
did
didn
die
died
diego
dies
differ
different
difficult
difficulti
dig
dilemma
diner
dinner
dinosaur
diplomat
dire
direct
director
dirt
dirti
dirtycop
disabl
disappear
disappears
disast
disaster
disastr
discov
discoveri
diseas
disease
disfigur
disgrac
disguis
dishonesti
disillus
disney
disord
dispatch
disrupt
distant
district
distrust
disturb
ditch
diva
dive
divid
divis
divorc
divorce
dj
dna
doc
doctor
document
documentari
dodg
doe
doesn
dog
doll
dollar
dolphin
dolphlundgren
domest
domin
don
donaldpetri
donaldsutherland
doncheadl
donnel
doom
doomsday
door
doorstep
doppelgang
dorothi
doubl
double
doublecross
doublelif
doubt
doug
dougliman
dr
dracula
drag
dragon
drama
dramat
draw
drawn
dread
dream
dreams
dress
drew
drewbarrymor
drift
drifter
drink
drive
driven
driver
drone
drop
drown
drug
drugabus
drugaddict
drugdeal
druglord
drugs
drugsmuggl
drugtraff
drugus
drunk
drunken
du
dualident
dub
duck
dude
duel
duke
dump
duo
dure
duringcreditssting
dustinhoffman
dutch
duti
dwarv
dwaynejohnson
dyinganddeath
dylan
dynam
dynasti
dysfunct
dysfunctionalfamili
dystopia
dystopicfutur
eager
earli
earlier
earn
earth
earthquak
easi
easili
east
eat
eccentr
econom
economi
eddi
eddiegriffin
eddiemurphi
edg
edgar
edharri
editor
educ
edward
edwardburn
edwardnorton
edwardzwick
effect
effort
egg
ego
egypt
egyptian
el
elabor
elderli
elect
element
eleph
elev
eliaskotea
elijahwood
elimin
elisabethshu
elit
elite
elizabeth
elizabethbank
ella
ellenburstyn
ellenpag
elli
elliot
elliott
els
elud
elus
elv
elvi
embark
embassi
embroil
emerg
emigr
emilehirsch
emili
emilyblunt
emilymortim
emilywatson
emma
emmarobert
emmaston
emmathompson
emmawatson
emot
emperor
empir
empire
employ
employe
enabl
enchant
encount
encourag
end
endless
endoftheworld
endur
enemi
enemies
enemy
energi
enforc
engag
engin
england
english
enigmat
enjoy
enlist
enorm
enrol
ensemblecast
ensu
ensues
ensur
entangl
enter
enterpris
entertain
enthusiast
entir
entiti
environ
environment
epic
epidem
episod
equal
era
eric
ericbana
erin
ernest
erotic
erupt
escap
escapad
escape
escapefromprison
escort
especi
espionag
establish
estat
estrang
etern
ethan
ethancoen
ethanhawk
ethic
eugenelevi
europ
european
eva
evacu
evad
evamend
evanrachelwood
eve
event
events
eventu
eventually
everi
everybodi
everyday
everyon
everyth
evid
evil
evolut
evolv
ewanmcgregor
ex
exact
exactli
exam
examin
exchang
excit
exclus
execut
exercis
exhibit
exil
exist
existence
existenti
exorc
exot
exoticisland
expect
expected
expedit
experi
experienc
experience
experiment
expert
explain
explod
exploit
explor
explos
expos
extend
extra
extramaritalaffair
extraordinari
extraterrestri
extraterrestrialtechnolog
extrem
extremeviol
eye
eyes
fabl
fac
face
facil
fact
faction
factori
fade
fail
fairi
fairytal
faith
fake
falcon
fall
fallen
fallinginlov
fals
falseident
falselyaccus
fame
famili
families
family
familyconflict
familyrelationship
famkejanssen
famou
famous
fan
fanat
fangvamp
fans
fantasi
fantast
fantasyworld
far
farewel
farm
farmer
fascin
fashion
fast
faster
fat
fatal
fate
father
fatherdaughterrelationship
fathersonrelationship
favor
favorit
fbi
fbiagent
fear
fearless
fearsom
featur
fed
feder
feed
feel
feet
fellow
femal
female
femalecorps
femalefriendship
femalenud
femaleprotagonist
fend
festiv
festival
fetish
feud
fi
fiance
fiancé
fiction
fictionalplac
field
fierc
fifth
fight
fighter
figur
fil
file
film
filmdirector
filmmak
filmproduc
films
final
finale
financ
financi
fine
finish
finn
firemen
firework
firm
firsttim
fish
fisherman
fishoutofwat
fistfight
fit
fix
flame
flash
flashback
flat
fledgl
flee
flesh
fli
flight
fling
flint
flirt
flood
florida
florist
flower
flyingsauc
focu
focus
foe
foil
foley
folk
follow
food
foot
footag
footbal
footchas
forbidden
forbiddenlov
forc
force
forces
ford
foreign
forest
forestwhitak
forev
forever
forg
forget
forgiv
form
formid
formula
fort
fortun
fortune
fortunetel
forward
foster
fought
foundfootag
fourth
fox
frame
franc
france
francisco
francisfordcoppola
frank
frankcoraci
frankenstein
franki
frankoz
frantic
fratern
fraud
freak
fred
freddi
freddieprinzejr
free
freedom
freeman
freez
french
frequent
fresh
freshman
friend
friendli
friends
friendship
frighten
frog
fromragstorich
frontier
frozen
frustrat
fu
fuel
fugit
fulfil
fulli
fun
fund
funer
funeral
furiou
futur
future
futurist
fword
ga
gabriel
gabrielbyrn
gadget
gaelgarcíabern
gain
galaxi
galaxy
gambl
gambler
game
games
gandhi
gang
gangs
gangster
gangsterboss
gangwar
garag
garden
gari
garrymarshal
garygray
garyoldman
garysinis
gasstat
gate
gather
gave
gay
gayinterest
gayrelationship
genehackman
gener
general
generation
genet
geniu
genius
gentl
geoffreyrush
georg
george
georgea
georgeclooney
georgemil
georgia
gerardbutl
german
germani
germany
getaway
ghetto
ghost
giant
giantrobot
gift
gig
girl
girlfriend
girls
given
glamor
glass
glennclos
global
globe
glori
goal
god
goe
gold
golden
golf
gone
good
goodvsevil
gordon
gore
gorgeou
gorilla
gossip
got
gotham
gothamc
gotten
govern
government
governor
grace
grad
grade
gradual
graduat
grand
grandfath
grandfather
grandmoth
grandmother
grant
graphic
grasp
grave
great
greater
greatest
greec
greed
greedi
greek
green
greg
gregkinnear
gregorypeck
grew
grief
griev
griffin
grim
grip
grisli
ground
group
groupoffriend
grow
growingup
grown
gruesom
gu
guard
guardian
guerrilla
guest
guid
guilt
guitar
gun
gunfight
gunman
gunsling
guru
gusvans
guy
guypearc
guyritchi
guys
gwynethpaltrow
gym
gypsi
ha
hack
hacker
hair
haleyjoelos
half
hall
halleberri
halloween
hallucin
han
hand
handl
hands
handsom
handtohandcombat
hang
hangov
hannah
hansel
hapless
happen
happens
happi
happili
happiness
happy
hara
harass
harbor
hard
harder
harlem
harmoni
harold
haroldrami
harri
harriet
harrison
harrisonford
harrow
harry
harsh
hart
harvard
harvey
harveykeitel
hasn
hatch
hate
hatr
haunt
hauntedhous
haven
havoc
hawaii
haydenchristensen
haze
head
headlin
heal
health
hear
heard
heart
heartattack
heartbreak
heat
heather
heathergraham
heathledg
heaven
heavi
heavili
heavymet
height
heir
heiress
heist
held
helen
helenabonhamcart
helenhunt
helenmirren
helicopt
hell
help
henchmen
henri
hero
heroes
heroic
heroin
heroism
hi
hidden
hiddencamera
hide
high
higher
highest
highland
highli
highschool
highschoolsport
highschoolstud
highway
hijack
hike
hilari
hilaryduff
hilaryswank
hill
himalaya
hip
hippi
hire
histor
histori
historicalfigur
history
hit
hitch
hitchhik
hitman
ho
hobbit
hockey
hold
hole
holi
holiday
holli
hollywood
home
homeinvas
homeland
homeless
homelessperson
hometown
homicid
homophobia
homosexu
honey
honeymoon
hong
hongkong
honor
hood
hoodlum
hook
hop
hope
hopedavi
hopelessli
hord
horribl
horrif
horrifi
horror
hors
horsebackrid
horserac
hospit
hospital
host
hostag
hostage
hostil
hot
hotel
hotelroom
hotshot
hour
hous
house
household
housewif
howard
howev
hud
huge
hugh
hughgrant
hughjackman
human
humananimalrelationship
humanity
humankind
humans
humili
humor
hundr
hunger
hungri
hunt
hunter
hunters
hurrican
hurt
husband
hustler
hypnosi
hypnot
hyster
ianmckellen
ice
icecub
icon
idea
ideal
idealist
ident
identity
idol
idyl
ignit
ignor
ii
iii
ill
illeg
illegaldrug
illegalimmigr
illegalprostitut
illness
illus
illustr
imag
imagin
imaginari
imagined
imax
immedi
immens
immigr
immort
impact
imperi
imperson
implic
import
imposs
impostor
impress
imprison
inadvert
incest
incid
includ
incompet
increas
increasingli
incred
independ
independentfilm
indi
india
indian
indiana
indianlead
individu
industri
industry
inevit
inexplic
infam
infant
infect
infidel
infiltr
influenc
inform
inhabit
inherit
initi
inject
injur
injuri
inmat
inner
innoc
insan
insecur
insid
insight
insist
insomnia
inspector
inspir
instal
instant
instantli
instead
instinct
institut
institution
instructor
insur
insurg
intellig
intend
intens
intent
intergalact
intern
internet
interpret
interrog
interspeciesrom
intertwin
interview
intim
intoler
intrigu
introduc
invad
invas
invent
inventor
invest
investig
investigate
invis
invit
involv
iowa
ira
iran
iranian
iraq
iraqwar
ireland
irish
iron
islam
island
isn
isol
isra
israel
issu
itali
italian
ivanreitman
jack
jackass
jackblack
jacki
jackiechan
jacknicholson
jackson
jacob
jadapinkettsmith
jade
jail
jake
jakegyllenha
jamaica
jame
james
jamescaan
jamescameron
jamesfranco
jamesivori
jamesmangold
jamesmarsden
jamesmcavoy
jameswan
jameswood
jami
jamie
jamiefoxx
jamieleecurti
jan
jane
janitor
japan
japanes
jaredleto
jason
jasonbateman
jasonbigg
jasonle
jasonschwartzman
jasonsegel
jasonstatham
javierbardem
jay
jaychandrasekhar
jayroach
jazz
jealousi
jean
jeanreno
jedi
jeff
jeffbridg
jeffdaniel
jeffgoldblum
jennif
jenniferaniston
jenniferconnelli
jennifergarn
jenniferjasonleigh
jenniferlawr
jenniferlopez
jenniferlovehewitt
jeremyiron
jeremyrenn
jerri
jersey
jerusalem
jess
jessebradford
jesseeisenberg
jessica
jessicaalba
jessicabiel
jessicachastain
jesu
jesus
jesuschrist
jetli
jew
jewel
jewish
jigsaw
jill
jim
jimbroadb
jimcarrey
jimcaviezel
jimmi
jimmy
jin
joanallen
joancusack
joaquinphoenix
job
jobinterview
jock
jodiefost
joe
joedant
joel
joelcoen
joeledgerton
joelschumach
joepesci
joey
john
johnc
johncarpent
johncusack
johngoodman
johnhurt
johnkrasinski
johnleguizamo
johnmalkovich
johnmctiernan
johnni
johnny
johnnydepp
johnnyknoxvil
johnsingleton
johnson
johntravolta
johnturturro
johnwoo
join
jon
jonahhil
jonathan
jonathanfrak
jonathanrhysmey
jone
jones
jonfavreau
jonturteltaub
jonvoight
jordan
joseph
josephgordon
josh
joshbrolin
joshhartnett
joshhutcherson
journal
journalist
journey
joy
jr
juan
judelaw
judg
judidench
juli
julia
julian
juliannemoor
juliarobert
juliastil
julie
jump
jungl
jungle
junior
junki
just
justic
justice
justinlong
justintimberlak
kansa
karat
karen
karlurban
kat
kate
katebeckinsal
katebosworth
katehudson
katemara
katewinslet
katherin
katherineheigl
kathi
kathyb
kati
katieholm
katniss
kay
keanureev
keiraknightley
kelli
kelly
kellypreston
ken
kennethbranagh
kermit
kevin
kevinbacon
kevincostn
kevinhart
kevinjam
kevinklin
kevinsmith
kevinspacey
key
kgb
khan
kick
kid
kidnap
kidnapp
kidnapped
kids
kidsandfamili
kiefersutherland
kill
killed
killer
killerrobot
killers
kim
kimbasing
kind
king
kingdom
kingpin
kirk
kirstendunst
kiss
kit
kitchen
knew
knife
knight
knit
knock
know
knowledg
known
kong

In [52]:
from sklearn.metrics.pairwise import cosine_similarity

In [53]:
similarity=cosine_similarity(vector)

In [54]:
similarity[0]

array([1.        , 0.08585457, 0.08718573, ..., 0.04559608, 0.        ,
       0.        ])

In [55]:
sorted(list(enumerate(similarity[65])),reverse=True,key=lambda x:x[1])[1:20]

[(3, 0.42256142372325745),
 (119, 0.40218090755486674),
 (428, 0.33142090599966445),
 (299, 0.2941494555969643),
 (1359, 0.2608360150191666),
 (210, 0.260063165868498),
 (4134, 0.25537695922762454),
 (9, 0.2512448876271439),
 (4635, 0.2407717061715384),
 (3853, 0.23052135826937487),
 (1873, 0.2175844552560732),
 (2914, 0.21669453555438456),
 (4098, 0.21234068575686865),
 (3726, 0.2106752429000961),
 (4224, 0.2043850068658243),
 (4389, 0.20033416898825337),
 (3725, 0.19702760155977517),
 (3453, 0.1947939014230696),
 (205, 0.1933288618331376)]

In [56]:
def recommend(movied):
    movie_index=movie[movie['title']==movied].index[0]
    distance=similarity[movie_index]
    movie_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movie_list:
        print(movie.iloc[i[0]].title)

In [57]:
recommend('Alice in Wonderland')

Alice Through the Looking Glass
Mirrormask
Snow White and the Huntsman
The Snow Queen
Marie Antoinette

In [58]:
movie.head()

,movie_id,title,tag
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [59]:
filters=movie.merge(ratings,on='movie_id')

In [60]:
filters.shape

(16724, 6)

In [61]:
filters.head(10)

,movie_id,title,tag,userId,rating,timestamp
0,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c...",604,4.0,832080636
1,58,Pirates of the Caribbean: Dead Man's Chest,captain jack sparrow work hi way out of a bloo...,4,3.0,964538444
2,58,Pirates of the Caribbean: Dead Man's Chest,captain jack sparrow work hi way out of a bloo...,5,5.0,847435238
3,58,Pirates of the Caribbean: Dead Man's Chest,captain jack sparrow work hi way out of a bloo...,7,3.0,1106635520
4,58,Pirates of the Caribbean: Dead Man's Chest,captain jack sparrow work hi way out of a bloo...,23,3.0,1107164183
5,58,Pirates of the Caribbean: Dead Man's Chest,captain jack sparrow work hi way out of a bloo...,32,5.0,856736227
6,58,Pirates of the Caribbean: Dead Man's Chest,captain jack sparrow work hi way out of a bloo...,33,4.0,939646784
7,58,Pirates of the Caribbean: Dead Man's Chest,captain jack sparrow work hi way out of a bloo...,74,5.0,1207502891
8,58,Pirates of the Caribbean: Dead Man's Chest,captain jack sparrow work hi way out of a bloo...,90,5.0,856354071
9,58,Pirates of the Caribbean: Dead Man's Chest,captain jack sparrow work hi way out of a bloo...,91,2.0,1112710933

In [62]:
def build_user_profile(user_id, ratings_df, movie_vectors, movie_df):
    user_rated = ratings_df[(ratings_df['userId'] == user_id) & (ratings_df['rating'] >= 4)]    
    movie_indices = movie_df[movie_df['movie_id'].isin(user_rated['movie_id'])].index
    if len(movie_indices) == 0:
        return None    
    user_profile = movie_vectors[movie_indices].mean(axis=0)  # Trung bình các vector
    return user_profile

In [63]:
# def recommend_movies_for_user(user_id, ratings_df, movie_vectors, movie_df, top_n=20, sim_threshold=0.24):
#     user_profile = build_user_profile(user_id, ratings_df, movie_vectors, movie_df)
#     if user_profile is None:
#         return ["User chưa có phim nào rated cao."]
    
#     sim_scores = cosine_similarity([user_profile], movie_vectors)[0]
#     watched_ids = ratings_df[ratings_df['userId'] == user_id]['movieId'].tolist()
#     movie_df['sim'] = sim_scores
#     recommendations = movie_df[~movie_df['movieId'].isin(watched_ids)]
#     recommendations = recommendations[recommendations['sim'] > sim_threshold].sort_values(by='sim', ascending=False)
#     return recommendations[['title', 'sim']].head(top_n)

In [64]:
def recommend_movies_for_user(user_id, ratings_df, similarity, movie_df, top_n=5):
    liked_movie_ids = ratings_df[(ratings_df['userId'] == user_id) & (ratings_df['rating'] >= 4)]['movie_id'].tolist()
    if not liked_movie_ids:
        return ["User chưa có phim nào rated cao."]    
    liked_indices = movie_df[movie_df['movie_id'].isin(liked_movie_ids)].index.tolist()
    if not liked_indices:
        return ["Không tìm thấy phim user đã thích trong movie_df."]
    
    sim_scores = similarity[liked_indices].mean(axis=0)    
    # Loại bỏ các phim đã xem
    watched_ids = ratings_df[ratings_df['userId'] == user_id]['movie_id'].tolist()
    movie_df = movie_df.copy()
    movie_df['sim'] = sim_scores
    recommendations = movie_df[~movie_df['movie_id'].isin(watched_ids)].sort_values(by='sim', ascending=False)    
    return recommendations[['movie_id', 'title', 'sim']].head(top_n)

In [65]:
unique_movies = filters[['movie_id', 'title', 'tag']].drop_duplicates('movie_id').reset_index(drop=True)

In [66]:
recommend_movies_for_user(1, filters, similarity, movie)

      movie_id                  title       sim
697      37165        The Truman Show  0.135493
1247     13536        City By The Sea  0.133912
2346     11904  Young Sherlock Holmes  0.131333
3726     11826             Sexy Beast  0.131157
4143     20406               Rockaway  0.131040

In [67]:
print(filters.columns)

Index(['movie_id', 'title', 'tag', 'userId', 'rating', 'timestamp'], dtype='object')

In [68]:
print(unique_movies.columns)

Index(['movie_id', 'title', 'tag'], dtype='object')

In [69]:
num_users = ratings['userId'].nunique()
print(f"Tổng số người dùng là: {num_users}")

Tổng số người dùng là: 610